DECLARE
    table_missing EXCEPTION;
    PRAGMA EXCEPTION_INIT(table_missing, -942);

    PROCEDURE drop_table_if_exists(p_table_name IN VARCHAR2) IS
    BEGIN
        EXECUTE IMMEDIATE 'DROP TABLE ' || p_table_name || ' CASCADE CONSTRAINTS PURGE';
    EXCEPTION
        WHEN table_missing THEN
            NULL;
    END;
BEGIN
    drop_table_if_exists('email_retry_logs');
    drop_table_if_exists('email_send_logs');
    drop_table_if_exists('hot_deal_products');
    drop_table_if_exists('hot_deals');
    drop_table_if_exists('reviews');
    drop_table_if_exists('purchases');
    drop_table_if_exists('visits');
    drop_table_if_exists('favorites');
    drop_table_if_exists('product_pictures');
    drop_table_if_exists('product_options');
    drop_table_if_exists('products');
    drop_table_if_exists('promotions');
    drop_table_if_exists('user_auth');
    drop_table_if_exists('categories');
    drop_table_if_exists('users');
END;
/

CREATE TABLE users (
    id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    email VARCHAR2(255) NOT NULL,
    password VARCHAR2(255) NOT NULL,
    name VARCHAR2(100) NOT NULL,
    gender VARCHAR2(20) NOT NULL,
    birth DATE NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    deleted_at TIMESTAMP,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT chk_users_gender CHECK (gender IN ('MALE', 'FEMALE', 'OTHER'))
);

CREATE TABLE user_auth (
    auth_no NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    user_id NUMBER(19) NOT NULL,
    auth VARCHAR2(50) NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT pk_user_auth PRIMARY KEY (auth_no),
    CONSTRAINT uk_user_auth UNIQUE (user_id, auth),
    CONSTRAINT fk_ua_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT chk_ua_auth CHECK (auth IN ('ROLE_USER', 'ROLE_ADMIN'))
);

CREATE TABLE categories (
    id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    name VARCHAR2(100) NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT pk_categories PRIMARY KEY (id),
    CONSTRAINT uk_categories_name UNIQUE (name)
);

CREATE TABLE products (
    id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    category_id NUMBER(19) NOT NULL,
    name VARCHAR2(255) NOT NULL,
    description CLOB,
    price NUMBER(10) NOT NULL,
    view_count NUMBER(10) DEFAULT 0 NOT NULL,
    status VARCHAR2(30) DEFAULT 'ON_SALE' NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT pk_products PRIMARY KEY (id),
    CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT chk_products_price CHECK (price >= 0),
    CONSTRAINT chk_products_view CHECK (view_count >= 0),
    CONSTRAINT chk_products_status CHECK (status IN ('ON_SALE', 'SOLD_OUT', 'STOPPED'))
);

CREATE TABLE product_pictures (
    id NUMBER(19) 			GENERATED BY DEFAULT ON NULL AS IDENTITY,
    product_id 				NUMBER(19) 		NOT NULL,
    picture_saved_location 	VARCHAR2(1000) 	NOT NULL,
    display_order 			NUMBER(10) 		DEFAULT 1 NOT NULL,
    created_at 				TIMESTAMP 		DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at 				TIMESTAMP,
    
    CONSTRAINT pk_product_pictures PRIMARY KEY (id),
    CONSTRAINT fk_pictures_products FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE,
    CONSTRAINT uk_product_pictures_location UNIQUE (product_id, picture_saved_location),
    CONSTRAINT uk_product_pictures_order UNIQUE (product_id, display_order),
    CONSTRAINT chk_product_pictures_order CHECK (display_order > 0)
);

CREATE TABLE product_options (
    id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    product_id NUMBER(19) NOT NULL,
    stock NUMBER(10) DEFAULT 0 NOT NULL,
    expire_date DATE NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT pk_product_options PRIMARY KEY (id),
    CONSTRAINT fk_options_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE,
    CONSTRAINT chk_options_stock CHECK (stock >= 0)
);

CREATE TABLE favorites (
    user_id NUMBER(19) NOT NULL,
    product_id NUMBER(19) NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT pk_favorites PRIMARY KEY (user_id, product_id),
    CONSTRAINT fk_favorites_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_favorites_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE
);

CREATE TABLE visits (
    user_id NUMBER(19) NOT NULL,
    product_id NUMBER(19) NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT pk_visits PRIMARY KEY (user_id, product_id),
    CONSTRAINT fk_visits_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_visits_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE
);

CREATE TABLE purchases (
    id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    user_id NUMBER(19) NOT NULL,
    product_option_id NUMBER(19),
    quantity NUMBER(10) NOT NULL,
    purchase_price NUMBER(10) NOT NULL,
    total_price NUMBER(30) GENERATED ALWAYS AS (quantity * purchase_price) VIRTUAL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT pk_purchases PRIMARY KEY (id),
    CONSTRAINT fk_purchases_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_purchases_option FOREIGN KEY (product_option_id) REFERENCES product_options (id),
    CONSTRAINT chk_purchases_qty CHECK (quantity > 0),
    CONSTRAINT chk_purchases_price CHECK (purchase_price >= 0)
);

CREATE TABLE reviews (
    id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    user_id NUMBER(19) NOT NULL,
    product_id NUMBER(19) NOT NULL,
    purchase_id NUMBER(19) NOT NULL,
    rating NUMBER(1) NOT NULL,
    content CLOB,
    img_src VARCHAR2(1000),
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    deleted_at TIMESTAMP,
    CONSTRAINT pk_reviews PRIMARY KEY (id),
    CONSTRAINT uk_reviews_purchase UNIQUE (purchase_id),
    CONSTRAINT fk_reviews_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_reviews_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT fk_reviews_purchase FOREIGN KEY (purchase_id) REFERENCES purchases (id),
    CONSTRAINT chk_reviews_rating CHECK (rating BETWEEN 1 AND 5)
);

CREATE TABLE hot_deals (
    id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    created_by NUMBER(19) NOT NULL,
    title VARCHAR2(255) NOT NULL,
    description CLOB,
    starts_at TIMESTAMP NOT NULL,
    ends_at TIMESTAMP NOT NULL,
    status VARCHAR2(30) DEFAULT 'SCHEDULED' NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    deleted_at TIMESTAMP,
    CONSTRAINT pk_hot_deals PRIMARY KEY (id),
    CONSTRAINT fk_hot_deals_user FOREIGN KEY (created_by) REFERENCES users (id),
    CONSTRAINT chk_hot_deals_status CHECK (status IN ('SCHEDULED', 'ACTIVE', 'ENDED', 'DELETED')),
    CONSTRAINT chk_hot_deals_period CHECK (ends_at > starts_at)
);

CREATE TABLE hot_deal_products (
    hot_deal_id NUMBER(19) NOT NULL,
    product_option_id NUMBER(19) NOT NULL,
    original_price NUMBER(10) NOT NULL,
    hot_deal_price NUMBER(10) NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_hot_deal_products PRIMARY KEY (hot_deal_id, product_option_id),
    CONSTRAINT fk_hdp_hot_deal FOREIGN KEY (hot_deal_id) REFERENCES hot_deals (id) ON DELETE CASCADE,
    CONSTRAINT fk_hdp_product FOREIGN KEY (product_option_id) REFERENCES product_options (id),
    CONSTRAINT chk_hdp_price CHECK (original_price >= 0 AND hot_deal_price >= 0 AND hot_deal_price <= original_price)
);

CREATE TABLE email_send_logs (
    id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    hot_deal_id NUMBER(19),
    user_id NUMBER(19) NOT NULL,
    recipient_email VARCHAR2(255) NOT NULL,
    title VARCHAR2(255) NOT NULL,
    content CLOB,
    status VARCHAR2(30) DEFAULT 'PENDING' NOT NULL,
    retry_count NUMBER(5) DEFAULT 0 NOT NULL,
    failure_reason CLOB,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT pk_email_send_logs PRIMARY KEY (id),
    CONSTRAINT fk_esl_hot_deal FOREIGN KEY (hot_deal_id) REFERENCES hot_deals (id),
    CONSTRAINT fk_esl_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT chk_esl_status CHECK (status IN ('PENDING', 'SENT', 'FAILED', 'RETRYING')),
    CONSTRAINT chk_esl_retry CHECK (retry_count >= 0)
);

CREATE TABLE email_retry_logs (
    id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    email_send_log_id NUMBER(19) NOT NULL,
    retry_count NUMBER(5) NOT NULL,
    failure_reason CLOB NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_email_retry_logs PRIMARY KEY (id),
    CONSTRAINT fk_erl_send_log FOREIGN KEY (email_send_log_id) REFERENCES email_send_logs (id) ON DELETE CASCADE,
    CONSTRAINT chk_erl_retry CHECK (retry_count > 0)
);

CREATE TABLE promotions (
    id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    title VARCHAR2(255) NOT NULL,
    img_src VARCHAR2(1000) NOT NULL,
    link VARCHAR2(1000),
    display_order NUMBER(10) NOT NULL,
    starts_at TIMESTAMP NOT NULL,
    ends_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT pk_promotions PRIMARY KEY (id),
    CONSTRAINT uk_promotions_order UNIQUE (display_order),
    CONSTRAINT chk_promotions_order CHECK (display_order > 0),
    CONSTRAINT chk_promotions_period CHECK (ends_at > starts_at)
);

CREATE INDEX idx_product_category 	ON products (category_id);
CREATE INDEX idx_product_status 	ON products (status);
CREATE INDEX idx_option_expire 		ON product_options (expire_date);
CREATE INDEX idx_option_stock 		ON product_options (stock);
CREATE INDEX idx_favorite_product 	ON favorites (product_id);
CREATE INDEX idx_visit_product 		ON visits (product_id);
CREATE INDEX idx_purchase_user 		ON purchases (user_id);
CREATE INDEX idx_purchase_option 	ON purchases (product_option_id);
CREATE INDEX idx_review_user 		ON reviews (user_id);
CREATE INDEX idx_review_product 	ON reviews (product_id);
CREATE INDEX idx_hot_deal_status 	ON hot_deals (status, starts_at, ends_at);
CREATE INDEX idx_esl_status 		ON email_send_logs (status);
CREATE INDEX idx_esl_user 			ON email_send_logs (user_id);
